import { ScrollText } from "lucide-react";

import { LegalPage, type LegalSection } from "@/shared/ui/legal-page";

const sections: LegalSection[] = [
  {
    title: "Acceptance of Terms",
    body: "By accessing or using mAgenticX, you agree to be bound by these Terms and Conditions. If you do not agree to all of these terms, you may not access or use the platform. Your continued use of the platform following any modifications to these terms constitutes your acceptance of those changes.",
  },
  {
    title: "Description of Service",
    body: "mAgenticX is a multi-agent AI chat platform that provides AI-assisted conversations, document retrieval, and agentic task execution. The service is provided as-is and may be updated, modified, or discontinued at any time without prior notice. We reserve the right to change features, pricing, and availability at our discretion.",
  },
  {
    title: "User Accounts",
    body: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account or any other breach of security. We reserve the right to terminate accounts, remove content, or cancel services at our discretion, with or without notice.",
  },
  {
    title: "Acceptable Use",
    body: "You agree not to use mAgenticX for any unlawful purpose or in any way that could damage, disable, or impair the service. This includes transmitting harmful or malicious content, attempting unauthorized access to any part of the service, interfering with its proper functioning, scraping or harvesting data without permission, or violating any applicable laws or regulations.",
  },
  {
    title: "Intellectual Property",
    body: "All content, features, and functionality of mAgenticX — including but not limited to source code, design, logos, and documentation — are the exclusive property of mAgenticX and are protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written consent.",
  },
  {
    title: "AI-Generated Content",
    body: "Responses generated by AI agents are for informational purposes only. We do not guarantee the accuracy, completeness, or reliability of AI-generated content. You are solely responsible for how you use, interpret, and act upon any AI-generated output. mAgenticX expressly disclaims any liability for decisions made based on AI responses.",
  },
  {
    title: "Data and Privacy",
    body: "Your use of the platform is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using mAgenticX, you consent to the data practices described in the Privacy Policy. We handle your data with care and in accordance with applicable privacy regulations.",
  },
  {
    title: "Limitation of Liability",
    body: "To the fullest extent permitted by law, mAgenticX and its affiliates, officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including loss of profits, data, or goodwill — arising from your use of or inability to use the service.",
  },
  {
    title: "Modifications to Terms",
    body: "We reserve the right to modify these Terms at any time. When we make changes, we will update the date at the top of this page. Material changes will be communicated through a notice on the platform or via email where feasible. Continued use of the service after changes are posted constitutes your acceptance of the revised Terms.",
  },
  {
    title: "Governing Law",
    body: "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the competent courts in the applicable jurisdiction.",
  },
];

export default function TermsAndConditions() {
  return (
    <LegalPage
      icon={<ScrollText size={18} />}
      title="Terms & Conditions"
      heading="Terms of Service"
      intro={
        "Please read these Terms carefully before using mAgenticX. They govern your access to and use of the platform and all its services."
      }
      lastUpdated="May 2025"
      version="v1.0"
      idPrefix="tc"
      sections={sections}
      footer={
        <>
          Questions about these Terms? Contact us through the{" "}
          <span className="font-semibold text-foreground">Support</span> section in the Help tab of
          your profile settings.
        </>
      }
    />
  );
}
