import { useEffect, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { ScrollText } from "lucide-react";
import { StaticPageHeader } from "@/shared/ui/static-page-header";
import { cn } from "@/shared/lib/utils";

const sections = [
  {
    title: "Acceptance of Terms",
    body: "By accessing or using mAgenticX, you agree to be bound by these Terms and Conditions. If you do not agree to all of these terms, you may not access or use the platform. Your continued use of the platform following any modifications to these terms constitutes your acceptance of those changes.",
  },
  {
    title: "Description of Service",
    body: "mAgenticX is a multi-agent AI chat platform that provides AI-assisted conversations, document retrieval, and agentic task execution. The service is provided as-is and may be updated, modified, or discontinued at any time without prior notice. We reserve the right to change features, pricing, and availability at our discretion.",
  },
  {
    title: "User Accounts",
    body: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account or any other breach of security. We reserve the right to terminate accounts, remove content, or cancel services at our discretion, with or without notice.",
  },
  {
    title: "Acceptable Use",
    body: "You agree not to use mAgenticX for any unlawful purpose or in any way that could damage, disable, or impair the service. This includes transmitting harmful or malicious content, attempting unauthorized access to any part of the service, interfering with its proper functioning, scraping or harvesting data without permission, or violating any applicable laws or regulations.",
  },
  {
    title: "Intellectual Property",
    body: "All content, features, and functionality of mAgenticX — including but not limited to source code, design, logos, and documentation — are the exclusive property of mAgenticX and are protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written consent.",
  },
  {
    title: "AI-Generated Content",
    body: "Responses generated by AI agents are for informational purposes only. We do not guarantee the accuracy, completeness, or reliability of AI-generated content. You are solely responsible for how you use, interpret, and act upon any AI-generated output. mAgenticX expressly disclaims any liability for decisions made based on AI responses.",
  },
  {
    title: "Data and Privacy",
    body: "Your use of the platform is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using mAgenticX, you consent to the data practices described in the Privacy Policy. We handle your data with care and in accordance with applicable privacy regulations.",
  },
  {
    title: "Limitation of Liability",
    body: "To the fullest extent permitted by law, mAgenticX and its affiliates, officers, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including loss of profits, data, or goodwill — arising from your use of or inability to use the service.",
  },
  {
    title: "Modifications to Terms",
    body: "We reserve the right to modify these Terms at any time. When we make changes, we will update the date at the top of this page. Material changes will be communicated through a notice on the platform or via email where feasible. Continued use of the service after changes are posted constitutes your acceptance of the revised Terms.",
  },
  {
    title: "Governing Law",
    body: "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the competent courts in the applicable jurisdiction.",
  },
];

const ease: [number, number, number, number] = [0.22, 1, 0.36, 1];

export default function TermsAndConditions() {
  const shouldReduce = useReducedMotion();
  const [activeSection, setActiveSection] = useState(0);

  useEffect(() => {
    const observers = sections.map((_, i) => {
      const el = document.getElementById(`tc-section-${i}`);
      if (!el) return null;
      const observer = new IntersectionObserver(
        ([entry]) => {
          if (entry.isIntersecting) setActiveSection(i);
        },
        { rootMargin: "-20% 0px -65% 0px" },
      );
      observer.observe(el);
      return observer;
    });
    return () => observers.forEach((o) => o?.disconnect());
  }, []);

  const handleTocClick = (e: React.MouseEvent<HTMLAnchorElement>, i: number) => {
    e.preventDefault();
    document
      .getElementById(`tc-section-${i}`)
      ?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <div className="min-h-screen bg-background">
      <StaticPageHeader icon={<ScrollText size={18} />} title="Terms & Conditions" />

      <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6">
        {/* Hero */}
        <motion.div
          initial={shouldReduce ? false : { opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, ease }}
          className="mb-10"
        >
          <div className="relative overflow-hidden rounded-3xl border border-border bg-card p-8">
            <div className="pointer-events-none absolute -right-20 -top-20 h-56 w-56 rounded-full bg-primary/8 blur-3xl" />
            <div className="pointer-events-none absolute -bottom-10 -left-10 h-40 w-40 rounded-full bg-primary/5 blur-2xl" />
            <div className="relative flex flex-wrap items-end justify-between gap-4">
              <div>
                <p className="text-[0.65rem] font-bold uppercase tracking-[0.2em] text-primary">
                  Legal
                </p>
                <h2 className="mt-2 text-3xl font-semibold tracking-tight text-foreground">
                  Terms of Service
                </h2>
                <p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">
                  Please read these Terms carefully before using mAgenticX. They govern your access
                  to and use of the platform and all its services.
                </p>
              </div>
              <div className="flex flex-col items-end gap-1 text-right">
                <span className="text-xs text-muted-foreground">Last updated</span>
                <span className="text-sm font-semibold text-foreground">May 2025</span>
                <span className="mt-1 rounded-full border border-border bg-muted px-2.5 py-0.5 text-[0.65rem] font-semibold text-muted-foreground">
                  v1.0
                </span>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Body: TOC + Document */}
        <motion.div
          initial={shouldReduce ? false : { opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.15, ease }}
          className="lg:grid lg:grid-cols-[13rem,1fr] lg:gap-10"
        >
          {/* Sticky TOC */}
          <aside className="mb-8 lg:mb-0">
            <div className="sticky top-24">
              <p className="mb-3 text-[0.6rem] font-bold uppercase tracking-[0.2em] text-muted-foreground">
                Contents
              </p>
              <nav className="space-y-0.5">
                {sections.map((s, i) => (
                  <a
                    key={i}
                    href={`#tc-section-${i}`}
                    onClick={(e) => handleTocClick(e, i)}
                    className={cn(
                      "flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-xs transition-colors",
                      activeSection === i
                        ? "bg-primary/8 font-semibold text-primary"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground",
                    )}
                  >
                    <span
                      className={cn(
                        "flex h-4 w-4 shrink-0 items-center justify-center rounded-full text-[0.55rem] font-bold transition-colors",
                        activeSection === i
                          ? "bg-primary/15 text-primary"
                          : "bg-muted-foreground/10 text-muted-foreground",
                      )}
                    >
                      {i + 1}
                    </span>
                    <span className="leading-tight">{s.title}</span>
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Document */}
          <div className="min-w-0">
            <div className="rounded-3xl border border-border bg-card">
              {sections.map((section, i) => (
                <section
                  key={section.title}
                  id={`tc-section-${i}`}
                  className={cn(
                    "scroll-mt-24 px-8 py-8",
                    i < sections.length - 1 && "border-b border-border/60",
                  )}
                >
                  <div className="flex items-start gap-5">
                    <span className="mt-0.5 shrink-0 text-[0.6rem] font-bold uppercase tracking-[0.18em] text-primary/60">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <div className="min-w-0">
                      <h2 className="text-base font-semibold text-foreground">{section.title}</h2>
                      <p className="mt-3 text-sm leading-7 text-muted-foreground">{section.body}</p>
                    </div>
                  </div>
                </section>
              ))}
            </div>

            <div className="mt-6 rounded-2xl border border-border bg-muted/40 px-6 py-5">
              <p className="text-xs leading-relaxed text-muted-foreground">
                Questions about these Terms? Contact us through the{" "}
                <span className="font-semibold text-foreground">Support</span> section in the Help
                tab of your profile settings.
              </p>
            </div>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
