"""baseline — initial schema snapshot

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-05

This is the **baseline** migration. It reproduces the schema previously created
by ``Base.metadata.create_all`` so that:

  - A fresh local/CI database can reach the current schema via
    ``alembic upgrade head`` instead of relying on ``create_all``.
  - The Dennis production database — which already has every table — can be
    marked at this revision via ``alembic stamp 0001_baseline`` without
    touching any data. ``alembic upgrade`` then becomes a no-op until a real
    migration is added on top.

Hand-written (not autogenerated) so the cross-FK cycle between conversations
and messages can be expressed cleanly (use_alter=True), and the partial
indexes on ``messages.streaming_status`` are captured verbatim. Any future
schema change goes in a NEW migration on top — never edit this one.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum names referenced by messages.sender / messages.type. Declared once so
# upgrade/downgrade share the same Postgres type identifiers. The enums are
# created/dropped IMPLICITLY by create_table("messages")/drop_table — each is
# used by exactly one table, so it is emitted exactly once. We deliberately do
# NOT also call .create() explicitly: that double-created the type (CREATE TYPE
# ... already exists) on a real `alembic upgrade`. The bug stayed latent because
# every existing environment was `alembic stamp 0001_baseline`'d (this upgrade
# never ran) until a from-scratch migrate exposed it. (Note: sa.Enum's
# create_type kwarg is postgresql.ENUM-specific and a no-op on generic sa.Enum,
# so it cannot suppress the implicit create — dropping the explicit call does.)
_MESSAGE_SENDER_ENUM = sa.Enum("user", "ai", name="message_sender_enum")
_MESSAGE_TYPE_ENUM = sa.Enum("text", "file", "image", "audio", "tool", name="message_type_enum")


def upgrade() -> None:
    # Enums are created implicitly by create_table("messages") below (each is
    # used by exactly one table → emitted once). No explicit .create() here —
    # see the module-level note on the double-create bug.

    # ------------------------------------------------------------------
    # agents
    # ------------------------------------------------------------------
    op.create_table(
        "agents",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("slug", name="uq_agents_slug"),
    )

    # ------------------------------------------------------------------
    # users
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("vault_user_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.Column("role_title", sa.String(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.UniqueConstraint("vault_user_id", name="uq_users_vault_user_id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_username", "users", ["username"])
    op.create_index("ix_users_vault_user_id", "users", ["vault_user_id"])
    op.create_index("ix_users_email", "users", ["email"])

    # ------------------------------------------------------------------
    # user_preferences
    # ------------------------------------------------------------------
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("prefers_agentic_chat", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("suggestions_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("voice_mode_voice", sa.String(), nullable=False, server_default="alloy"),
        sa.Column("voice_mode_language", sa.String(), nullable=False, server_default="english"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id", name="uq_user_preferences_user_id"),
    )
    op.create_index("ix_user_preferences_user_id", "user_preferences", ["user_id"])

    # ------------------------------------------------------------------
    # blobs — created before attachments which references it
    # ------------------------------------------------------------------
    op.create_table(
        "blobs",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )

    # ------------------------------------------------------------------
    # conversations — cross-FKs to messages declared with use_alter so the
    # circular dependency (conversations ↔ messages) can be resolved after
    # both tables exist.
    # ------------------------------------------------------------------
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("forked_parent_id", sa.String(), nullable=True),
        sa.Column("forked_message_id", sa.String(), nullable=True),
        sa.Column("agent_name", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("is_archived", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("is_reported", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("reported_at", sa.DateTime(), nullable=True),
        sa.Column("active_assistant_message_id", sa.String(), nullable=True),
        sa.Column("last_message_preview", sa.String(), nullable=True, server_default=""),
        sa.Column("last_message_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["forked_parent_id"], ["conversations.id"], ondelete="SET NULL"
        ),
    )
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])
    op.create_index("ix_conversations_agent_id", "conversations", ["agent_id"])
    op.create_index("ix_conversations_forked_parent_id", "conversations", ["forked_parent_id"])
    op.create_index("ix_conversations_forked_message_id", "conversations", ["forked_message_id"])
    op.create_index(
        "ix_conversations_active_assistant_message_id",
        "conversations",
        ["active_assistant_message_id"],
    )

    # ------------------------------------------------------------------
    # messages
    # ------------------------------------------------------------------
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("parent_message_id", sa.String(), nullable=True),
        sa.Column("sender", _MESSAGE_SENDER_ENUM, nullable=False),
        sa.Column("type", _MESSAGE_TYPE_ENUM, nullable=False, server_default="text"),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("liked", sa.Boolean(), nullable=True),
        sa.Column("reasoning_steps", sa.JSON(), nullable=True),
        sa.Column("reasoning_time_seconds", sa.Integer(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("raw_events", sa.JSON(), nullable=True),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.Column("subagents", sa.JSON(), nullable=True),
        sa.Column("streaming_status", sa.String(), nullable=True),
        sa.Column("streaming_message_path", sa.JSON(), nullable=True),
        sa.Column("streaming_enabled_tools", sa.JSON(), nullable=True),
        sa.Column("streaming_started_at", sa.DateTime(), nullable=True),
        sa.Column("streaming_completed_at", sa.DateTime(), nullable=True),
        sa.Column("streaming_cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_message_id"], ["messages.id"], ondelete="SET NULL"
        ),
    )
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_index("ix_messages_parent_message_id", "messages", ["parent_message_id"])
    # Partial unique: at most one active streaming row per conversation. Mirrors
    # the Index() declaration in core.database.MessageTable.__table_args__.
    op.create_index(
        "uq_messages_one_active_stream_per_conversation",
        "messages",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("streaming_status IN ('queued', 'running', 'cancelling')"),
        sqlite_where=sa.text("streaming_status IN ('queued', 'running', 'cancelling')"),
    )
    op.create_index(
        "ix_messages_streaming_status",
        "messages",
        ["streaming_status"],
        postgresql_where=sa.text("streaming_status IS NOT NULL"),
        sqlite_where=sa.text("streaming_status IS NOT NULL"),
    )

    # ------------------------------------------------------------------
    # Resolve the conversations ↔ messages cross-FKs now that both exist.
    # ------------------------------------------------------------------
    op.create_foreign_key(
        "fk_conversations_active_assistant_message_id_messages",
        "conversations",
        "messages",
        ["active_assistant_message_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_conversations_forked_message_id_messages",
        "conversations",
        "messages",
        ["forked_message_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ------------------------------------------------------------------
    # conversation_reports
    # ------------------------------------------------------------------
    op.create_table(
        "conversation_reports",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="open"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("conversation_id", name="uq_conversation_reports_conversation_id"),
    )
    op.create_index("ix_conversation_reports_conversation_id", "conversation_reports", ["conversation_id"])
    op.create_index("ix_conversation_reports_user_id", "conversation_reports", ["user_id"])
    op.create_index("ix_conversation_reports_message_id", "conversation_reports", ["message_id"])

    # ------------------------------------------------------------------
    # conversation_shares
    # ------------------------------------------------------------------
    op.create_table(
        "conversation_shares",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("snapshot_until_message_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_until_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("token", name="uq_conversation_shares_token"),
    )
    op.create_index("ix_conversation_shares_token", "conversation_shares", ["token"])
    op.create_index("ix_conversation_shares_conversation_id", "conversation_shares", ["conversation_id"])
    op.create_index("ix_conversation_shares_owner_user_id", "conversation_shares", ["owner_user_id"])
    op.create_index("ix_conversation_shares_snapshot_until_message_id", "conversation_shares", ["snapshot_until_message_id"])
    op.create_index("ix_conversation_shares_expires_at", "conversation_shares", ["expires_at"])

    # ------------------------------------------------------------------
    # attachments
    # ------------------------------------------------------------------
    op.create_table(
        "attachments",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("blob_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["blob_id"], ["blobs.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_attachments_message_id", "attachments", ["message_id"])
    op.create_index("ix_attachments_blob_id", "attachments", ["blob_id"])

    # ------------------------------------------------------------------
    # sessions
    # ------------------------------------------------------------------
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("access_token_hash", sa.String(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=False),
        sa.Column("prev_refresh_token_hash", sa.String(), nullable=True),
        sa.Column("access_expires_at", sa.DateTime(), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("user_agent_hash", sa.String(), nullable=True),
        sa.Column("ip_hash", sa.String(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("access_token_hash", name="uq_sessions_access_token_hash"),
        sa.UniqueConstraint("refresh_token_hash", name="uq_sessions_refresh_token_hash"),
    )
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"])
    op.create_index("ix_sessions_access_token_hash", "sessions", ["access_token_hash"])
    op.create_index("ix_sessions_refresh_token_hash", "sessions", ["refresh_token_hash"])
    op.create_index("ix_sessions_prev_refresh_token_hash", "sessions", ["prev_refresh_token_hash"])


def downgrade() -> None:
    # Drop in reverse dependency order. Cross-FKs on conversations are removed
    # before messages so messages can be dropped cleanly.
    op.drop_index("ix_sessions_prev_refresh_token_hash", table_name="sessions")
    op.drop_index("ix_sessions_refresh_token_hash", table_name="sessions")
    op.drop_index("ix_sessions_access_token_hash", table_name="sessions")
    op.drop_index("ix_sessions_user_id", table_name="sessions")
    op.drop_table("sessions")

    op.drop_index("ix_attachments_blob_id", table_name="attachments")
    op.drop_index("ix_attachments_message_id", table_name="attachments")
    op.drop_table("attachments")

    op.drop_index("ix_conversation_shares_expires_at", table_name="conversation_shares")
    op.drop_index("ix_conversation_shares_snapshot_until_message_id", table_name="conversation_shares")
    op.drop_index("ix_conversation_shares_owner_user_id", table_name="conversation_shares")
    op.drop_index("ix_conversation_shares_conversation_id", table_name="conversation_shares")
    op.drop_index("ix_conversation_shares_token", table_name="conversation_shares")
    op.drop_table("conversation_shares")

    op.drop_index("ix_conversation_reports_message_id", table_name="conversation_reports")
    op.drop_index("ix_conversation_reports_user_id", table_name="conversation_reports")
    op.drop_index("ix_conversation_reports_conversation_id", table_name="conversation_reports")
    op.drop_table("conversation_reports")

    op.drop_constraint(
        "fk_conversations_forked_message_id_messages",
        "conversations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_conversations_active_assistant_message_id_messages",
        "conversations",
        type_="foreignkey",
    )

    op.drop_index("ix_messages_streaming_status", table_name="messages")
    op.drop_index("uq_messages_one_active_stream_per_conversation", table_name="messages")
    op.drop_index("ix_messages_parent_message_id", table_name="messages")
    op.drop_index("ix_messages_conversation_id", table_name="messages")
    op.drop_table("messages")

    op.drop_index("ix_conversations_active_assistant_message_id", table_name="conversations")
    op.drop_index("ix_conversations_forked_message_id", table_name="conversations")
    op.drop_index("ix_conversations_forked_parent_id", table_name="conversations")
    op.drop_index("ix_conversations_agent_id", table_name="conversations")
    op.drop_index("ix_conversations_user_id", table_name="conversations")
    op.drop_table("conversations")

    op.drop_table("blobs")

    op.drop_index("ix_user_preferences_user_id", table_name="user_preferences")
    op.drop_table("user_preferences")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_vault_user_id", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")

    op.drop_table("agents")
    # Enums are dropped implicitly by drop_table("messages") above; no explicit
    # .drop() (mirrors the implicit create in upgrade()).
