services:

  gateway: # 8005
    container_name: mcp_gateway
    image: docker/mcp-gateway:latest
    command:
    # Configure the MCP Gateway servers and transport
    - --transport=sse
    - --port=8005
    - --servers=tavily,arxiv-mcp-server
    # Point to the catalog, secrets and config files
    - --catalog=./app/mcp_catalog.yaml
    - --config=./app/mcp_config.yaml
    - --secrets=/app/mcp_secret
    volumes:
      - /opt/magenticx/mcp_config/mcp_catalog.yaml:/app/mcp_catalog.yaml:ro
      - /opt/magenticx/mcp_config/mcp_secret.env:/app/mcp_secret:ro
      - /opt/magenticx/mcp_config/mcp_config.yaml:/app/mcp_config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - gateway


networks:
  gateway:
    driver: overlay
    attachable: true

