services:
  orthodoxai:
    container_name: orthodox_agent
    image: orthodox_agent
    build:
      context: ./orthodox_agents
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped


