services:

  orthodox_agents:
    container_name: orthodox_agents
    image: orthodox_agents
    build:
      context: ./orthodox_agents
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_HOST=rag_service
      - RAG_PORT=8001
    depends_on:
      - rag_service
    restart: unless-stopped
    networks:
      - backend
      - frontend

  rag_service:
    container_name: rag_service
    image: rag_service
    build: 
      context: ./rag_service
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_HOST=vectordb
      - RAG_PORT=8000
      - COLLECTION_NAME=athanasios-muthlinaios
    depends_on:
      - vectordb
    restart: unless-stopped
    networks:
      - backend
      - frontend

  vectordb:
    image: chromadb/chroma:0.6.3
    container_name: vectordb
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - vectorstore:/chroma/chroma
    restart: unless-stopped
    networks:
      - backend

  dialog_bridge:
    container_name: dialog_bridge
    image: dialog_bridge
    build:
      context: ./dialog_bridge
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@chat_postgres:5432/chat_db
    depends_on: 
      - orthodox_agents
      - chat_postgres
    ports:
      - "8002:8002"
    restart: unless-stopped
    networks: 
      - backend
      - frontend

  chat_postgres:
    image: postgres:latest
    container_name: chat_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat_db
    volumes:
      - chat_convs:/var/lib/postgresql/data
    networks:
      - backend


networks:
  backend:
    internal: true
  frontend: 


volumes:
  vectorstore:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./vectorstores/chroma_db_openai

  chat_convs:


