services:
  agents:
    container_name: agents
    image: konstantinosmpouros/agents:v1.2.0
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_HOST=rag_service
      - RAG_PORT=8001
    depends_on:
      - rag_service
    restart: unless-stopped
    networks:
      - backend
      - frontend

  rag_service:
    container_name: rag_service
    image: konstantinosmpouros/rag_service:v1.1.0
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_HOST=vectordb
      - RAG_PORT=8000
    depends_on:
      - vectordb
    restart: unless-stopped
    networks:
      - backend
      - frontend

  vectordb:
    image: chromadb/chroma:0.6.3
    container_name: vectordb
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - vectorstore:/chroma/chroma
    restart: unless-stopped
    networks:
      - backend

  dialogue_bridge:
    container_name: dialogue_bridge
    image: konstantinosmpouros/dialogue_bridge:v1.0.5
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@chat_postgres:5432/chat_db
      - username=${username}
      - password=${password}
    depends_on:
      - agents
      - chat_postgres
    restart: unless-stopped
    networks:
      - backend

  chat_postgres:
    image: postgres:latest
    container_name: chat_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat_db
    volumes:
      - chat_convs:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  streamlit_app:
    container_name: streamlit_app
    image: konstantinosmpouros/streamlit_app:v1.0.5
    environment:
      - BFF_HOST=dialogue_bridge
      - BFF_PORT=8002
    depends_on:
      - dialogue_bridge
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - backend
      - frontend


networks:
  backend:
    internal: true
  frontend: 


volumes:
  vectorstore:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kostas/vectorstores/chroma_db_openai

  chat_convs: