import { describe, expect, it } from "vitest";

import {
  transformAgent,
  transformConversationDetail,
  transformConversationSummary,
  transformMessage,
} from "@/shared/lib/consts";

/**
 * The wire→app transform layer is field-whitelisted: a backend field that is not
 * named here is silently dropped, with no type error and no runtime warning.
 * That has already caused two shipped bugs — a generated attachment rendering as
 * a plain upload, and privacy depending on key casing — so these tests pin the
 * fields whose loss is invisible until a user notices.
 */

describe("transformConversationSummary / Detail", () => {
  it("reads isPrivate in either casing and defaults to public", () => {
    // Fail-closed matters more here than anywhere else in the mapper: a dropped
    // privacy flag renders a private conversation as a public one.
    expect(transformConversationSummary({ id: "c1", isPrivate: true }).isPrivate).toBe(true);
    expect(transformConversationSummary({ id: "c1", is_private: true }).isPrivate).toBe(true);
    expect(transformConversationSummary({ id: "c1" }).isPrivate).toBe(false);

    expect(transformConversationDetail({ id: "c1", is_private: true }).isPrivate).toBe(true);
  });

  it("reads archive and report metadata in either casing", () => {
    const snake = transformConversationSummary({
      id: "c1",
      is_archived: true,
      archived_at: "2026-01-02T03:04:05Z",
      is_reported: true,
    });
    expect(snake.isArchived).toBe(true);
    expect(snake.isReported).toBe(true);
    expect(snake.archivedAt).toBeInstanceOf(Date);
  });

  it("treats an active run as streaming", () => {
    expect(transformConversationSummary({ id: "c1", activeRunId: "r1" }).isStreaming).toBe(true);
    expect(transformConversationSummary({ id: "c1" }).isStreaming).toBe(false);
  });
});

describe("transformMessage", () => {
  it("carries attachment provenance through to the app shape", () => {
    // `origin` is what tells the UI a file was generated by the agent rather
    // than uploaded by the user. Dropping it double-rendered the artifact and
    // left its inline card stuck on "Preparing".
    const message = transformMessage({
      id: "m1",
      sender: "ai",
      attachments: [
        { id: "a1", name: "report.pdf", origin: "generated", title: "Report" },
        { id: "a2", name: "notes.txt" },
      ],
    });

    expect(message.attachments?.[0]).toMatchObject({
      origin: "generated",
      title: "Report",
    });
    // Anything without an explicit origin is an upload — never undefined, or
    // the generated-vs-upload split silently collapses.
    expect(message.attachments?.[1]).toMatchObject({ origin: "upload" });
  });

  it("reads per-message agent attribution in either casing", () => {
    expect(transformMessage({ id: "m1", agent_id: "a1", agent_name: "Ops" })).toMatchObject({
      agentId: "a1",
      agentName: "Ops",
    });
  });
});

describe("transformAgent", () => {
  it("resolves is_active from either casing and defaults to active", () => {
    expect(transformAgent({ id: "a1", is_active: false }).isActive).toBe(false);
    expect(transformAgent({ id: "a1", isActive: false }).isActive).toBe(false);
    expect(transformAgent({ id: "a1" }).isActive).toBe(true);
  });

  it("keeps iconName alongside the resolved component", () => {
    // The IndexedDB snapshot can only persist the name — a Lucide icon is a
    // forwardRef object whose `.name` is not the icon's name. Without this the
    // icon degrades to the fallback glyph on every reload.
    const agent = transformAgent({ id: "a1", icon: "Bot" });
    expect(agent.iconName).toBe("Bot");
    expect(agent.icon).toBeTruthy();
  });

  it("falls back to the supplied defaults when the agent is absent", () => {
    const agent = transformAgent(undefined, {
      id: "fallback",
      name: "Archived agent",
    });
    expect(agent).toMatchObject({
      id: "fallback",
      name: "Archived agent",
      isActive: true,
    });
  });

  it("ignores wrongly-typed fields rather than passing them through", () => {
    // Wire validation guarantees "this row is an object", not the type of each
    // field, so a malformed payload must not reach the UI typed as a string.
    const agent = transformAgent({ id: "a1", name: 42, description: null });
    expect(agent.name).toBe("Unknown Agent");
    expect(agent.description).toBe("");
  });
});
